//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGII_contribuyentes.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dato
    {
        public string RNC { get; set; }
        public string empresa { get; set; }
        public string empresa2 { get; set; }
        public string producto { get; set; }
        public string fecha_fundacion { get; set; }
        public string estado { get; set; }
        public string situacion { get; set; }
    }
}
